### ISSUE TITLE
When controller occurs before application controller

### ISSUE THREAD

**Issue by jeremylynch** [CanCanCommunity/cancancan#125]
I have the issue: 

```
undefined method `each_pair' for "new":String
# lib/mongoid/attributes/processing.rb:23:in `process_attributes'
```

The issue disappears when: 
- Removing `load_and_authorize_resource` and `check_authorization` from the controller (with the latest versions of devise(3.3.0) & cancancan(1.9.2) )
- When the controller is renamed so that it occurs alphabetically after the `application_controller.rb`.

To see this error run this app: https://github.com/mrjlynch/sample-mongoid-error-app and go to `localhost:3000/action/new`

**Comment by anilmaurya** [comment]
@mrjlynch Removing `load_and_authorize_resource` and `check_authorization` from the controller worked because issue is in `build_resource` method which is called by these methods internally.

After renaming controller, error didn't show up but your model  is not loaded correctly.

This error can also be avoided by defining `param_method` , see https://github.com/CanCanCommunity/cancancan#strong-parameters

**Comment by coorasse** [comment]
We do not support Mongoid in the main gem anymore.
