### ISSUE TITLE
Cannot use Hash as a resource

### ISSUE THREAD

**Issue by GeorgeDewar** [CanCanCommunity/cancancan#174]
I realise this is an unusual way to use CanCan, but I have noticed that the following fails unpredictably:

```
can :some_action, Hash do |params|
  # actual logic omitted
  puts params
  true
end
```

If I try ```can? :some_action, {a: 1}```, it will return false and *not run the block above at all*. If I try ```can? :some_action, {a: {a: 1}}```, it will behave correctly, printing ```{a: {a: 1}}```.

This appears to be due to rule.rb's *relevant* method, which contains the following code:

```
    24: def relevant?(action, subject)
    25:   subject = subject.values.first if subject.class == Hash
    26:   @match_all || (matches_action?(action) && matches_subject?(subject))
    27: end
```

I'm curious what that is meant to do? Any thoughts? Is the use case so mad that it just should never be done?

The use case is basically where the subject is just one of several arbitrary parameters. For example, rather than "view a client", "view a client's financial projections" or "view a client's contact details". Any tips on how to achieve logic that goes beyond action and subject would be helpful also.

**Comment by GeorgeDewar** [comment]
I see that this behaviour doesn't occur if the subject is a subclass of Hash, such as ActionController::Parameters.

**Comment by Senjai** [comment]
@GeorgeDewar I'll look into this when I can, but I agree this case is not conventional. 

Ideally, you should never be passing in a `Hash` here. An object can have a hash for its internal data structure, but I would recommend actually modeling your application with classes representative of the data they contain and operate on. 

I haven't dug into that yet, but I'm betting strongly that this won't be changed. Parameters doesn't get caught by this because it checks `class`, not `superclass`, nor does it use `is_a?`. When you pass a hash, I believe it is expecting a list of conditions.
