### ISSUE TITLE
"can :create, Model do" broken?

### ISSUE THREAD

**Issue by svoop** [CanCanCommunity/cancancan#200]
Given the following ability:

    can :create, Page do
      user.has_role?(:manager)
    end

The following has worked in the past:

    u = User.first
    u.has_role?(:manager)     # => false
    a = Ability.new u
    a.can? :create, Page   # => false

However, I just figured out that this no longer holds. The block passed to `can` in the definition is not hit unless you pass an instance, so this is what it looks like now:

    a.can? :create, Page       # => true - OOPS!
    a.can? :create, Page.new   # => false - OK

Is this a bug or a feature?

**Comment by eikes** [comment]
I just noticed this as well. It believe, that this is due to the ```!subject_class?(subject)``` condition of the first elsif clause [line 33 in rule.rb](https://github.com/CanCanCommunity/cancancan/blob/5fa747dd5441701b48356647d53ca213f7ca2e21/lib/cancan/rule.rb#L33) 

```ruby
    # Matches the block or conditions hash
    def matches_conditions?(action, subject, extra_args)
      if @match_all
        call_block_with_all(action, subject, extra_args)
      elsif @block && !subject_class?(subject)
        @block.call(subject, *extra_args)
      elsif @conditions.kind_of?(Hash) && subject.class == Hash
        nested_subject_matches_conditions?(subject)
      elsif @conditions.kind_of?(Hash) && !subject_class?(subject)
        matches_conditions_hash?(subject)
      else
        # Don't stop at "cannot" definitions when there are conditions.
        conditions_empty? ? true : @base_behavior
      end
    end
```

The example given in the [Ability.rb](https://github.com/CanCanCommunity/cancancan/blob/5fa747dd5441701b48356647d53ca213f7ca2e21/lib/cancan/ability.rb#L39-L46) won't work under these circumstances either:

```ruby
    # Any additional arguments will be passed into the "can" block definition. This
    # can be used to pass more information about the user's request for example.
    
    can? :create, Project, request.remote_ip
    
    can :create, Project do |project, remote_ip|
      # ...
    end
```

**Comment by eikes** [comment]
I wrote a test that verifies that this does not work. Pull request is here: https://github.com/CanCanCommunity/cancancan/pull/206

**Comment by Senjai** [comment]
@svoop @eikes I've been able to reproduce this easily. Thanks for your example eikes.

I noted there are specific tests guarding against this behavior, @svoop do you remember when this has worked for you or what version this worked in?

**Comment by svoop** [comment]
@Senjai I've tried to find the moment when it actually broke, but to no avail. However, it must have happened quite a while ago, the faulty behavior appears to be present in 1.7.1 already, maybe even quite a bit earlier.

**Comment by anthonylewis** [comment]
I believe this is working as designed. See the docs on the wiki here:

https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks#only-for-object-attributes

> The block is **only** evaluated when an actual instance object is present.

Changing this behavior would cause problems in my app and probably others.

This has worked this way since CanCan 1.4 back in October 2010:

https://github.com/ryanb/cancan/wiki/Defining-Abilities-with-Blocks/99f3b8e4c38e78bb14f9e24e854b1615f4141fea

> As of 1.4, the block is not called when checking permission on a class...

**Comment by Honeybunch** [comment]
I agree that this is by design; I was just working with this sort of situation. If you pass a block or a hash to a `can` it will only execute if you call `can?` with an instance of a class.

**Comment by Senjai** [comment]
@Honeybunch @anthonylewis I agree that this is by design, because there are specific test cases for ensuring that the former behavior does not occur. However the documentation for this is obviously confusing. Would either of you consider updating it?

As far as I know, this is due to the mechanic around accessible by which doesn't want to call a block for each item in the collection. This makes sense from a performance perspective, but isn't intuitive. We should probably raise an exception to ensure that users do not accidentally run into this scenario, and possibly look at making it more intuitive moving forward as we drop old ruby/AR support.

**Comment by Senjai** [comment]
I would accept a PR for the aforementioned by the way.

**Comment by Honeybunch** [comment]
I've updated the wiki a bit. I hope it's clear! 
I'm not actually able to contribute code right now because of work obligations (sorry :cry: )

**Comment by anthonylewis** [comment]
@Honeybunch I (hopefully) clarified the wording a bit and made the example more explicit on the wiki.

@Senjai you propose raising `ArgumentError` when an ability check with a block is called with a class instead of an instance? I'll see if I can make that happen.

**Comment by anthonylewis** [comment]
@Senjai I have code to raise `ArgumentError` when `can` is defined with a block and `can?` is called with a class, but I'm not sure this is the right solution. This would certainly not be a backwards compatible change.

**Comment by eikes** [comment]
You'll probably want to change the inline documentation in [Ability.rb](https://github.com/CanCanCommunity/cancancan/blob/5fa747dd5441701b48356647d53ca213f7ca2e21/lib/cancan/ability.rb#L39-L46) as well.

**Comment by Senjai** [comment]
@anthonylewis I agree, it might be best simply to display a warning message for now and fix the documentation. I think this should be an ArgumentError in the next major if the behavior stays as is.

**Comment by Senjai** [comment]
@eikes @anthonylewis @svoop I did some actual research on this.

As mentioned by the OP, the block is invoked correctly when an instance is passed in, but without an instance, the block isn't called and thus behaves like a normal `can :create, Post` statement and allows the rule to pass. I think this is where the source of the confusion comes from. 

We can make this clear in the documentation by stating that this is a scenario that can occur, encouraging the following:

```ruby
  if can_create_global_posts?
    can :create, Post do |post, conditions|
      #...
    end
  end
```

The problem here is that passing this rule would mean that the user can create Posts, but only if certain instance specific conditions are passed. 

So in a controller, if I `authorize! :create, Post`, I would be able to bypass the instance specific authorization if I didn't recheck the authorization with the specific instance. This is why the create action for example assigns attributes to the instance before `authorize!`'ing that instance though this behavior isn't consistent with the update action. 

Open to suggestions.

**Comment by eikes** [comment]
@Senjai Why are you closing this if there is no fix in the develop branch?
