### ISSUE TITLE
Problem load_instance? returning true even when :class option is set to false

### ISSUE THREAD

**Issue by OriaLogic** [CanCanCommunity/cancancan#278]
Hello,

We have have a Resource-like controller with no model class backing it. I tried to use the following:
```
class App::IntegrationsController < ApplicationController
  authorize_resource :'app/integrations', class: false, parent: false
  ...
```
as advised in https://github.com/CanCanCommunity/cancancan/wiki/Non-RESTful-Controllers.

And then in models/ability.rb
```can :manage, :'app/integrations'```

But when trying to access an action of this controller (App:IntegrationsController), I get the error
```@app/integrations' is not allowed as an instance variable name```

I found out that the problems comes from:
in resource_instancecancancan (1.13.1) lib/cancan/controller_resource.rb
```
def resource_instance
  @controller.instance_variable_get("@#{instance_name}") if load_instance?
end
```

In lib/cancan/controller_resource.rb:
```
def load_instance?
    parent? || member_action?
end
```

What I do not understand is the fact that load_instance? returns true even when :class option is set to true?
Is there something I'm missing here?

Thanks in advance,
Lucas

**Comment by Senjai** [comment]
Authorize :'app/integrations' is silly. 99% of the time if your symbol actually has a string in it, you shouldn't be using a symbol. 

Using authorize resource with this is also silly, because you don't have a resource.

`before_filter :check_auth, -> { authorize! action, :app_integrations } `

**Comment by worldnamer** [comment]
Hey! Just ran into this bug today and spent a few hours tracking it down.

Couple things:

1. load_instance? is misused. It's called from two places: load_resource and resource_instance. In the former, nothing is executed if you've skipped loading. In the latter, it is always called. I think the latter should only call load_instance? if you're not skipping resource loading.

2. CanCan is using variables I've loaded but did not explicitly pass to CanCan. That is, the CanCan environment and my environment are not isolated properly. I'm explicitly telling the framework, through ```authorize_resource class: false``` that I don't want it to authorize from a resource, but through the name of the class. Now, simply because I have a variable defined, it ignores me - and possibly worse, fails authorization.

3. I think this can be fixed in one line, in CanCan::ControllerResource#resource_instance should now read:
```
    def resource_instance
      @controller.instance_variable_get("@#{instance_name}") if !skip?(:load) and load_instance?
    end
```

4. I believe you should also change CanCan::ControllerResource#collection_instance as well, because it's likely subject to the same problems as above, though this issue is separate.
