### ISSUE TITLE
Warning deprecation with rails 5

### ISSUE THREAD

**Issue by kaluznyo** [CanCanCommunity/cancancan#283]
Hi, 

Since Rails 4, before_filter was renamed to before_action. And with rails 5 using before_filter is deprecated. 

When I use authorize_resource I get DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.

This come from the method add_before_filter https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_resource.rb#L8

**Comment by piedoom** [comment]
Hi, I made a revision that should get rid of the issue - keep in mind I forked master, and I didn't test this thoroughly, but it should be fine since all I did is change the names to reflect the new methods.  I have a [link here](https://github.com/piedoom/portfolio), and I'll try to contribute to this project once I figure out how git works a little bit more :)

**Comment by Senjai** [comment]
Should be fixed now for rails 5
