### ISSUE TITLE
CanCanCan Create?

### ISSUE THREAD

**Issue by germs12** [CanCanCommunity/cancancan#285]
I have found that when I have an api that's loading and authorizing a resource, that I get issues if the conditions in the `ability.rb` file have a value for `:id`.  Specificially I get 

```bash
PG::UniqueViolation - ERROR:  duplicate key value violates unique constraint "loans_pkey"
DETAIL:  Key (id)=(1) already exists.
```

In my case the table is `loans`, but when my ability.rb file has this:

```ruby
can permission.name.to_sym, permission.subject_class.constantize, id: 1234
```
The first time it will correctly create the `Loan` object, but assign it a primary key value of `1234`.  The second time I create a `Loan` I get the `PG:UniqueViolation` because it's setting the `id` to `1234` again.  I would think you wouldn't want to allow a primary key to be automatically set.  Thoughts?

**Comment by Dgrady3** [comment]
I am also having the same issue. Any insight would be extremely helpful!

**Comment by kimrgrey** [comment]
@germs12 , when you initialize model using `load_resource` CanCanCan assigns attributes of created model using appropriate rules from `Ability`: https://git.io/vzTjZ. You had specified value `:id` in your rule, so this value has been assigned. But it's not correct for your model, so you have an error. 

Cancancan is using public rails setter to setup this attributes. If this assignment is not forbidden by Rails why it should be forbidden by CanCanCan? As for me there is only one minor change that is better to do here: use `public_send` instead of `send`.

**Comment by Senjai** [comment]
You cant create two objects with the same primary key in a database. I don't understand why this is a cancan issue.
