### ISSUE TITLE
Move RSpec matchers in their own module

### ISSUE THREAD

**Issue by syndbg** [CanCanCommunity/cancancan#297]
Due to the current state of [matchers.rb](https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/matchers.rb)

creating or including the matchers only for specific RSpec types is not possible.

Extracting matchers in their own module would solve this problem.

Examples:

job specific include

``` Ruby
require 'cancan/matchers'

# rails_helper
RSpec.configure do |config|
   config.include CanCan::Matchers, type: :model
end
```

**Comment by alexsanford** [comment]
I can see the appeal, although it would break backwards compatibility. Currently we can just `require 'cancan/matchers'` in our spec file and use the matchers right away. Putting them into a module would mean that we would have to require the file and then also include the module.

@Senjai what do you think? Maybe we could refactor this so that `require 'cancan/matchers'` does what it has always done, and then have a new file that includes just the module? Something like this:

```ruby
require 'cancan/matchers/module'

# rails_helper
RSpec.configure do |config|
   config.include CanCan::Matchers, type: :model
end
```

Thoughts?

**Comment by coorasse** [comment]
I close this issue for lack of interest. Feel free to open a PR to introduce that feature. Thanks
