### ISSUE TITLE
Can manage all overriding following rules

### ISSUE THREAD

**Issue by syndbg** [CanCanCommunity/cancancan#298]
`can :manage, :all` overrides following `can` rules implicitly.

Given the following ability:

``` Ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.superadmin?
      can :manage, :all
    elsif user.admin?
      can :manage, :all
      cannot :manage, User, role: User.roles[:superadmin]
    end
  end
end
```

This bug scenario happens

``` Ruby
> user = User.find_by(role: User.roles[:admin])
> ability = Ability.new(user)
> ability.can?(:manage, User, role: User.roles[:superadmin])
true
```

This completely neglects the usage of `cannot`

**Comment by cblavier** [comment]
:+1: Same issue here

**Comment by Fudoshiki** [comment]
same issue

**Comment by musialik** [comment]
I've had a closer look at this and wasn't able to reproduce this on `1.16.0`, `master`, `develop`.

I think the issue comes from misuse of the method `can?`.
The third argument in`can?` isn't a hash of conditions. It's an argument that is passed to the condition block. Also, when passing a class to `can?` the block isn't called.

In other words:
```ruby
# this
ability.can?(:manage, User, role: User.roles[:superadmin])
# is equivalent to this
ability.can?(:manage, User)
```
Which according to wiki and docs should be true.

To get the expected behavior you should pass an instance as argument:

```ruby
ability.can?(:manage, User.new(role: User.roles[:superadmin]))
```

Hope this helps.

**Comment by coorasse** [comment]
@musialik has given the right answer. Using `ability.can?(:manage, User, role: User.roles[:superadmin])` is the same as `ability.can?(:manage, User)` which makes also sense.
