### ISSUE TITLE
Replacing Cancan Model Adapters

### ISSUE THREAD

**Issue by lowjoel** [CanCanCommunity/cancancan#307]
I'm thinking of replacing the default AR adapter with my own, using the expressiveness of squeel, like in #296. Also, because I kind of need my queries to not eager load all the associated objects, in #238.

I'm thinking that I'd spawn a new gem for this new adapter, but I need to metaprogram and override `Cancan::Adapter::AbstractAdapter.for_class?`

Maybe we can spin off all the adapters to gems instead?

**Comment by lowjoel** [comment]
I've published the adapter as a gem: https://github.com/lowjoel/cancancan-squeel

I'm working on making the behaviour of the ability rules compatible with the AR adapter, but it doesn't appear that the AR adapter has got rules detailing how multiple rules are merged.

**Comment by coorasse** [comment]
Hei! Nice work! :+1:

**Comment by lowjoel** [comment]
I've added some additional specs for the adapter, specifically regarding how rules are combined, and what special attributes the adapter will recognise: https://github.com/lowjoel/cancancan-squeel/blob/master/spec/cancancan/squeel_spec.rb

It should be a superset of the tests for the AR4 adapter.

**Comment by Senjai** [comment]
I would love to have adapters pulled out. I'm fine with having a common active record adapter in CanCan, but mongoid and friends could be pulled out and maintained by people who have more domain knowledge in those areas. (I don't use mongodb, and largely have to rely on the community for those changes). I could pull these into the organization if it's desired.

I don't plan on adding squeel as a dependency though. The adapter problem is a long standing one, and there are PR's open for attempting to fix them, but each one adds quite a bit of complexity that honestly shouldn't be required. We should just be able to generate conditions the same way active record does instead of attempting to re implement the same interface ourselves. I've been looking into how to use the active record tools to do this to replace a lot of our adapter logic when I have time.

I understand the problem with eager loading that people are having, but I dont think adding an additional dependency is the right solution.

**Comment by coorasse** [comment]
To remove eager loading there is also this PR: https://github.com/CanCanCommunity/cancancan/pull/238

**Comment by lowjoel** [comment]
I don't think that my cancancan-squeel gem would ever be part of the main cancancan distribution, because I think it's overkill for most, except the most complex, applications.

However, I'm asking for two things:

1. specs regarding the behaviour of the AR adapter, especially with regards to rule merging and priorities
2. the ability to supersede the default AR adapter, without resorting to reopening the AR4 adapter class and replacing the for_class method.

The second is automatically handled by extracting all adapters into gems, unless an alternative approach is provided.

**Comment by lowjoel** [comment]
@Senjai After implementing this, I'm running into #265 again, and because it's a change to the way cancancan evaluates rules, it affects all adapters.

Maybe it would be good to draw up some plan regarding what the next set of refactoring will be, and we all can work towards that. I would not like to have all those PRs go stale.
