### ISSUE TITLE
Hash of conditions not working

### ISSUE THREAD

**Issue by ajeferson** [CanCanCommunity/cancancan#324]
I have a model called User and a controller called UsersController. I just want a basic authorization, that is to ensure that users can only edit a instance of the user model if the id matches the id of the current user. In my ability class I have the following:

`can :update, User, id: user.id`

However, it is possible to edit and update the users that does not match the current user's id.

Does someone know what is going on here?

Edit: I'm using authorize_resource, not load_and_authorize_resource

**Comment by ktec** [comment]
I'm getting the same results - basically it doesn't seem to work as described in the docs. I am yet to uncover why though.

**Comment by Senjai** [comment]
@ajeferson No idea. Can you provide some code that you think should work but doesn't? I have no idea how your checking permissions.

**Comment by CalvertYang** [comment]
@Senjai 

The [cancancan_issue_example](https://github.com/CalvertYang/cancancan_issue_example) is an example app to reproduce this issue.

I use `authorize_resource` in `PostsController` and set ability to `can :manage, Post, user: user`, but user2 still can update and destroy user1's post.

If uncomment `load_resource` in `PostsController`, the authorize procedure works fine!

**Comment by ktdmedia** [comment]
Also experiencing this on Rails (5.0.1) with cancancan (1.15.0).

**Comment by musialik** [comment]
@CalvertYang 
In your example, moving `authorize_resource` below `before_action :set_post` also makes it work.
That's because `authorize_resource` uses the loaded resource if it's available and falls back to running a check on the resource class.

And given this ability:

```ruby
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :manage, Post, user: user
  end
end
```
This will happen:
```ruby
user = User.find(1)
ability = Ability.new(user)

ability.can? :update, Post.new # => false
ability.can? :update, Post.new(user: user) # => true
ability.can? :update, Post # => true
```

This is why every user can update the records in your examples.
I'd say that this is a correct behavior, since `can? :update, Post` could be understood as "Can you update posts? Yes, some of them."
If you want `authorize_resource` to work as expected for `update`, you need to set the resource instance first.

**Comment by CalvertYang** [comment]
@musialik 
Thanks for your explanation.

It works like I expect, after I set the resource instance before `authorize_resource`.
