### ISSUE TITLE
How can I manipulate abilities for Devise?

### ISSUE THREAD

**Issue by bo-oz** [CanCanCommunity/cancancan#334]
Hi,

I'm trying to prevent access to certain user roles to the Devise sign-up page. I tried a lot of things in the Ability model, but nothing seems to work. Is there any information on this?

Thanks,

**Comment by walterdavis** [comment]
If a user is already signed in (at which point CanCan would be able to differentiate their abilities) then they can be kept out of parts of the Devise flow by extending the Devise controller and adding the authorize calls to the actions you want to restrict. But this sounds like a chicken-or-egg problem, because until they are signed in, they won't have any abilities (except those you grant to the guest user) and after they are signed in, they can't successfully sign up again without logging out.

Walter

**Comment by bo-oz** [comment]
Haha, didn't think of that yet. How should I achieve a admin controlled user registration. Can't it be done through standard devise?

**Comment by Senjai** [comment]
Hey @bo-oz we like to keep issues for project issues instead of a forum for questions. Please consider using stack overflow with the cancan tag if you're having problems.
