### ISSUE TITLE
Association autosave triggered by adding new model to collection

### ISSUE THREAD

**Issue by jimjamjoh** [CanCanCommunity/cancancan#399]
I have a model with a has_many association on another model and autosave set to true.

For example,

```ruby
class Game < ApplicationRecord
  has_many :players, autosave: true
end
```

In my controller, I have code similar to this:

```ruby
def addPlayer
  new_player = Player.new(params)
  game = Game.find_by_id(params[:game_id])
  
  game.players << new_player
  game.save
end
```

Before adding the cancancan gem, the collection did not attempt to insert the user until the call to game.save.  After adding cancancan, Rails tries to insert the new_player into the database _as soon as it's added to the players collection_ on the game object (the line before game.save).  If this fails any of my validations, it then throws a server exception and returns 500 to the requesting client.

Why is cancancan changing this behavior? How can I revert this so that cancancan does not change the default behavior?

**Comment by jimjamjoh** [comment]
By the way, I think that merely adding the cancancan gem changes some fundamental documented ActiveRecord behavior?  Previously I had models failing validations when calling Model.create (not create!) and building up the errors array.  After adding the gem, Model.create throws exceptions for failed validations.  Per the documentation, exceptions should only be thrown on Model.create! for failed validations.  Ideas?

**Comment by coorasse** [comment]
Can you follow the template and provide me a file to run that reproduces the issue? Thanks.
### Steps to reproduce

Please describe accurately how to reproduce the issue and post all necessary code.

If you provide a Gist to reproduce the issue this will make the debug much easier.

Please copy the following Gist and edit it to reproduce your issue: https://gist.github.com/coorasse/3f00f536563249125a37e15a1652648c

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**CanCanCan version**

**Comment by djhopper01** [comment]
Hi @jimjamjoh, I created a gist to try to reproduce the issue you described here: https://gist.github.com/djhopper01/f1864d7fce374b213ce3142937c490b6

I don't have cancancan enabled here, but the player is saved to the database. You can see on [line 57](https://gist.github.com/djhopper01/f1864d7fce374b213ce3142937c490b6) the test fails.

As far as I can tell from the Rails documentation, `<<` saves the record passed to it: http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-3C-3C

Were you able to find a solution to your problem?

**Comment by coorasse** [comment]
Closed because of starvation. 
Please feel free to reopen if this issue is still valid or interested in solving with a PR.
Thank you.
