### ISSUE TITLE
Checking with Class

### ISSUE THREAD

**Issue by kyleholzinger** [CanCanCommunity/cancancan#401]
This is more of a question than an issue, but it's regards to [this](https://github.com/CanCanCommunity/cancancan/wiki/Checking-Abilities#checking-with-class) entry in the wiki. Is this section implying that if you define a rule for a class, and pass `can?` the class itself, that it will always return true? I'm also confused by the explanation as to why you would ever want to do this, it mentions the `index` action but I don't see how that has anything to do with anything. It seems like the `authorize_resource` method just shouldn't authorize when the action is `index`, or would that be bad? Thanks in advance for the clarification! I'm sure I'm just misunderstanding something

**Comment by coorasse** [comment]
When you define an ability for a class `can :read, Book, interesting: true`, 
cancancan cannot answer the question "can I read books?" `can? :read, Book` because the answer would be "yes, but only the interesting ones". 

Since `can?` returns a boolean, there is no way to say "...but only the interesting ones" so it just tells you a generic "yes, you can read books". 

It can anyway answer the question "which books can I read?" `Book.accessible_by(user)` and return you the list containing only the interesting ones.

**Comment by kyleholzinger** [comment]
Is there any way to turn off that behavior? If it always returns true it seems unnecessarily confusing and bug prone @coorasse

**Comment by coorasse** [comment]
it may also return false if you define `cannot :read, Book`.

**Comment by kyleholzinger** [comment]
Is there any way to turn off this behavior all together? I don't want to be able to accidentally ever pass a class

**Comment by coorasse** [comment]
This is a semantically correct feature and I'm sorry but there is no way to disable a specific feature. 
You can monkey-patch the gem if you need to, but I'd rather suggest you to write tests so you don't accidentally do it ;).
