### ISSUE TITLE
Cancancan fails to compile SQL using `Model.accessible_by` on Rails 5.1 (arel 8.0)

### ISSUE THREAD

**Issue by ProGM** [CanCanCommunity/cancancan#424]
### Steps to reproduce

https://gist.github.com/ProGM/869356d5e17ad5fb0a1b0564a6e56181

### Expected behavior
It should build a query like this:
```sql
SELECT "books".* FROM "books" WHERE (("books"."user_id" = 1 AND "books"."status" = 0) OR ("books"."visibility" = 0))
```

### Actual behavior
It generates a broken query and fails:

```ruby
 1) Error:
BugTest#test_bug:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: books.user: SELECT "books".* FROM "books" WHERE (("books"."user" = 1 AND "books"."status" = 0) OR ("books"."visibility" = 0))
```

It fails to convert the expression` {:user=>#<User id: 1, ... >}` to `books.user_id = 1`

Inspecting the code, I think that this code for rails 5 is broken in some way:
https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/model_adapters/active_record_4_adapter.rb#L73

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

**CanCanCan version** 2.0.0

**Comment by coorasse** [comment]
Hey @ProGM , thanks for filling out the issue properly! 
I think the Wiki states that you have to use database columns (https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities#hash-of-conditions). Then you should use `can :manage, Book, user_id: user.id, status: 0`. 
I think is the intended behaviour but if you think otherwise and there are parts of the Wiki or documentation not clear or misleading please feel free to reopen the issue.

**Comment by ProGM** [comment]
Hi @coorasse,
Thank you for your answer!
Indeed using `user_id: user.id` works, but what I'm reporting is a change of behavior.

I was using Rails 5.0.2 with cancancan 2.0, and `can :manage, Book, user: user, status: 0` used to compile the correct query.

However, after upgrading to Rails 5.1.1, this behavior stopped working.

It's intended?

**Comment by joshpencheon** [comment]
I also came across this behaviour change in Rails; I've added a reproduction script here:

https://gist.github.com/joshpencheon/de6bcf946bfe3fe289e7cdba5b92bf67

I will swap to using the `column_name` rather than the `association_name`, as @coorasse suggests - I think the latter was just fortuitously working before.
