### ISSUE TITLE
Ability with conditions array behaving strangely for single objects

### ISSUE THREAD

**Issue by mgorman42** [CanCanCommunity/cancancan#430]
have a ability

can :manage, StopBlacklist, phone_code: phonecodes
That I know is getting hit for a given user

phonecodes is a list of phone_codes the user can mange stop blacklists for
and phone_code is the column on the table for stop blacklist

when I run accessible_by it returns the array of stop blacklist the user should be able delete as expected

>StopBlacklist.accessible_by(current_ability, :delete)

but when I run can? on a specific one in that list it run me false

>can? :delete, StopBlacklist.find(##)

I even tried to do the following

>can? :delete, StopBlacklist.accessible_by(current_ability, :delete)

and it returned false

I am using Cancancan version (1.17.0)
and Rails 4.0

Is there a reason using an array for the condition breaks checking on a single object?

EDIT

failing example

if phonecodes for the active user is [12345, 54321]

and there is a StopBlacklist with the values

id: 25
cell: 15555555555
phone_code: 12345

I would expect

 > current_ability.can? :delete, StopBlacklist.find 25

to return true, but it is returning false

but if I do

 > StopBlacklist.accessible_by(current_ability, :delete)

I find the StopBlacklist object with id 25 in the returned list

**Comment by coorasse** [comment]
Please follow the issue template and provide a failing example. Thank you!

**Comment by mgorman42** [comment]
I added a more specific example, thanks for the response.

**Comment by coorasse** [comment]
Please follow the template and provide a gist. I copy it here for you. This will help me understand your issue. Thanks.

### Steps to reproduce

Please describe accurately how to reproduce the issue and post all necessary code.

If you provide a Gist to reproduce the issue this will make the debug much easier.

Please copy the following Gist and edit it to reproduce your issue: https://gist.github.com/coorasse/3f00f536563249125a37e15a1652648c

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration
**Rails version**:

**Ruby version**:

**CanCanCan version**

**Comment by mgorman42** [comment]
Okay, while making the gist I think I figured out what is going on. it looks like the issue was that the array was an array of integers [12345, 54321].  but the value on the object was a string "12345", and the comparison wasn't working right, going to re-factor the phonecodes array to be strings

Thanks for your help.

**Comment by coorasse** [comment]
Glad I could help
