### ISSUE TITLE
`can?(:read)` always returns false when using query in ability

### ISSUE THREAD

**Issue by kaspernj** [CanCanCommunity/cancancan#442]
### Steps to reproduce

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'rails', '5.1.0'  # use correct rails version
  gem 'cancancan' # use correct cancancan version
  gem 'sqlite3' # use another DB if necessary
end

require 'active_record'
require 'cancancan'
require 'cancan/model_adapters/active_record_adapter'
require 'cancan/model_adapters/active_record_4_adapter'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

# create your tables here
ActiveRecord::Schema.define do
  create_table :books, force: true  do |t|
    t.integer :user_id
  end

  create_table :users, force: true  do |t|
    t.string :name
  end
end

class Book < ActiveRecord::Base
  belongs_to :user
end

class User < ActiveRecord::Base
  has_many :books
end

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Book, user_id: User.where(id: user.id)
  end
end

class BugTest < Minitest::Test
  def test_bug
    user1 = User.create!
    user2 = User.create!
    books = Book.create([{user: user1},{user: user2}])
    first_book = books.first
    ability = Ability.new(user1)
    books = Book.accessible_by(ability, :read).count
    assert_equal 1, books
    assert_equal true, ability.can?(:read, first_book)
  end
end
```

### Expected behavior
I expect that `can?(:read, book)` returns true but it doesn't.

### Actual behavior
`can?(:read, book)` always returns false. `Book.accessible_by(ability)` returns the expected book though.

### System configuration
**Rails version**:
5.1.4

**Ruby version**:
2.3.4

**CanCanCan version**
2.0.0

**Comment by laertispappas** [comment]
Isn't your ability definition wrong?

```ruby
def initialize(user)
    can :read, Book, user_id: User.where(id: user.id)   # <======= You should pass the user id here not an ActiveRecord::Relation
  end
```

**Comment by laertispappas** [comment]
I don't think that passing a relation should match the expected `user_id`. Why should one want to match a **single resource** with a **collection**?

This opens other questions that are hard to reason about. For example imagine that the relation passed in includes not only the authorized person but non authorized as well. How should we handle that?

I would prefer to keep it simple and strait forward on how to use the API on a **single resource** instead of providing multiple options on how to use the library. I have seen other libraries with multiple options to do the same thing and in the end they are just confusing and hard to understand.

**Comment by kaspernj** [comment]
@laertispappas I would then argue, that CanCanCan should reject collections all together. Right now I believe it does work with `accessible_by` but it doesn't work with `can?`.

I believe there are good arguments for using a collection. Here are some:

- It can be customised a lot more
- It can use existing scopes

**Comment by kaspernj** [comment]
I realise the query for the collection used here is oversimplified. Its just made for the reason of showing the usage in a test.

The query would probably join some tables and do some checks in a real life scenario and not just check the ID.

**Comment by laertispappas** [comment]
@kaspernj Thanks for your feedback. I do understand your concerns but `accessible_by` has a different nature than `can?` in my opinion. It is different to say give me all books accessible by the current ability for `:read` action than saying authorize that this book can be `:read` by these `:users` since you authorize one user per request so the statement is invalid by definition (again my point of view). 

I think it would add more value a real world example to discuss it. 
Thanks

**Comment by kaspernj** [comment]
@laertispappas I use `load_and_authorize_resource` a lot. My problem here was that my index action was working with the collection, but the show action wasn't. The reason being that index uses `accessible_by` and show uses `can?` (or `authorize`) which doesn't work with a collection.

I have a scope that I wished to use on my ability, which was done like this:

```ruby
can :read, Article, id: Article.my_scope.where("custom sql").where(access_table: {user_id: @user.id}) if @user
```

**Comment by laertispappas** [comment]
@kaspernj I see your point. You should also keep in mind the performance from the above query. I think that the above can be mapped to an array isn't that [supported?](https://github.com/CanCanCommunity/cancancan/wiki/defining-abilities)

```ruby
can :read, Article, id: Article.my_scope.
                        where("custom sql").
                        where(access_table: {user_id: @user.id}).
                        pluck(:id) if @user
```

What you are trying to implement I think is supported. Check the [defining abilities with scopes](https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities-with-Blocks) section maybe that will help you.

I would also consider to re architect your authorization scheme if it is to complicated (even though I don't think that is the case).

**Comment by coorasse** [comment]
Please refer to [Stackoverflow for questions](http://stackoverflow.com/questions/ask?tags=cancancan). Thanks.
