### ISSUE TITLE
load_and_authorize_resource not honouring :class

### ISSUE THREAD

**Issue by jnpoyser** [CanCanCommunity/cancancan#499]
I have a model called `'KPI'` - note casing

My controller is thus:
```
class KpisController < ApplicationController
   load_and_authorize_resource :class => KPI
   ...
```

(Yes, the controller class name casing is inconsistent)

But getting 'Unable to autoload constant Kpi' error

Rails 4.2.9, Ruby 2.3.4p301, Cancancan 2.2.0

**Comment by JrmKrb** [comment]
I actually have the same issue and looked into it into more details.

I decided to nest some models and controllers to make my code clearer, and get issues with load_and_authorize. The situation is the following:

I have a class `MyModule::ClassA` but since my nested controllers are different, I have a controller
`X::MyModule::ClassAsController` since I also have what I call non-X endpoints in my code.

I therefore load my resource like that:

```
class X::MyModule::ClassAsController < XController
    load_and_authorize_resource class: 'MyModule::ClassAsController'
    ...
```

The issue appears in the following method, in `cancancan/lib/cancan/controller_resource_name_finder.rb` 
```
    def namespaced_name
      [namespace, name].join('/').singularize.camelize.safe_constantize || name
    end
```

I think this method should use the `@options[:class]` that we provide instead of just using the namespace or name. In that case, it is looking for `X::MyModule::MyClass` instead of `MyModule::MyClass` and thus the same `LoadError` is raised as the safe_constantize tries to Load `MyClass` from `my_module/my_class` instead of `MyModule::MyClass`

In my case this works as expected if I put:

```
    def namespaced_name
        @options[:class].safe_constantize
    end
```

Shouldn't this method contain a case/when on `options[:class]` ?

I noted also that this only happens on the `new` action as in `controller_resource_loader.rb`, 

```
    def resource_params_by_namespaced_name
      resource_params_by_key(:instance_name) || resource_params_by_key(:class) || (
      params = @params[extract_key(namespaced_name)]
      params.respond_to?(:to_h) ? params : nil)
    end
```

`resource_params_by_key(:class)` is `nil` on my `new` action.

Is there already a way to configure CanCanCan to do what we want or should we fix somehow `namespaced_name` using `@options[:class]` ?

**Comment by coorasse** [comment]
Does `load_and_authorize_resource class: 'KPI'` work, instead?

**Comment by coorasse** [comment]
closing due to the lack of feedback. please feel free to re-open
