### ISSUE TITLE
Strange behaviour from accessible_by

### ISSUE THREAD

**Issue by evsasse** [CanCanCommunity/cancancan#570]
Two related problems I've been dealing with. I'm not sure with these are the correct ways to describe the abilities, because I dont have that much experience with cancancan, but are the ways we have been using them.

### Steps to reproduce

Having the abilities described such as:
```
# a Review is related to many Stores
# a Store is related to many Reviews

# the ids of the stores I can manage
manager_store_ids = [1, 2, 3, 4]
# the ids of the stores I cannot manage
# basically Store.where.not(id: manager_store_ids).pluck(:id)
not_manager_stores_ids = [5, 6, 7, 8]

# I can MANAGE all the reviews related to the stores I manage
can :manage, Review, review_stores: { store_id: manager_stores_ids }

# but cannot MANAGE the reviews that are related to any store I cannot manage
# this prevents me to MANAGE a review related to the stores [1, 2, 3, 4, 5]
# but allows me to MANAGE a review related to the stores [1, 2, 3, 4]
cannot :manage, Review, review_stores: { store_id: not_manager_stores_ids }

# even tough I cannot MANAGE the review related to the stores [1, 2, 3, 4, 5], I can READ it
can :read, Review, review_stores: { store_id: manager_stores_ids }
```

Now, to see the behaviours I need to set up a couple examples:
```
Review.create(id: 1, store_id: [1, 2, 3, 4])
Review.create(id: 2, store_id: [1, 2, 3, 4, 5])
Review.create(id: 3, store_id: [5, 6, 7, 8])
```

### Expected behavior

I expected that I could manage the first review, could only read the second review, and couldnt even read the third.
```
Review.all.map do |review|
  current_ability.can?(:read, review)
end
=> [true, true, false]  # success, I can read exactly these reviews

Review.all.map do |review|
  current_ability.can?(:update, review)
end
=> [true, false, false]  # success, I can update exactly these reviews
```

Also, that `accessible_by` would get me the following then:
```
Review.accessible_by(current_ability).pluck(:id)
=> [1, 2]  # success, I can read exactly these reviews

Review.accessible_by(current_ability, :update).pluck(:id)
=> [1]  # success, I can update exactly these reviews
```

#### Now, for the first problem... When using accessible_by:
```
Review.accessible_by(current_ability).pluck(:id)
=> [1, 2] # success, I can read exactly these reviews

Review.accessible_by(current_ability, :update).pluck(:id)
=> [1, 2] # Oops, I shouldnt be able to update the second review
```

The query is mounted differently from `Review.accessible_by(current_ability)` to `Review.accessible_by(current_ability, :update)`. It really tries to put the expected rules to use, but fails in doing so. I didnt really manage to pinpoint whats the problem with the query.

#### For the second problem... When using the result of the faulty accessible_by:

```
# lets recheck the result of this accessible_by
Review.accessible_by(current_ability, :update).map do |review|
  current_ability.can?(:manage, review)
end
=> [true, true] # strange... 🤔 

# lets recheck every review
Review.all.map do |review|
  current_ability.can?(:manage, review)
end
=> [true, false, false]
```

I suppose it tries to use some cached data of the `accessible_by` query to discover the result to the `can?`, and fails on the `can?` because of the faulty result of the `accessible_by`.

But... When using the `accessible_by` for read, that returns the correct results, `can?` also fails:
```
Review.accessible_by(current_ability).map do |review|
  current_ability.can?(:manage, review)
end
=> [true, true] # fails again 😕 
```

### System configuration
**Rails version**: 5.0.3

**Ruby version**: 2.4.1

**CanCanCan version**: 2.3.0

I don't really have the time this week to get deeper into this. But if you guys have could comment some questions I can get more info, and answer by next week. Also I could see into doing a reproducible example if necessary.

**Comment by coorasse** [comment]
[reproduction gist](https://gist.github.com/coorasse/b5ce12190f84f4490cd21e6299d798a7)

Allow me to reduce the problem to the following:

```ruby
can :read, Review, review_stores: { id: 1 }
cannot :read, Review, review_stores: { id: 2 }
review = Review.create(id: 1, store_id: [1, 2])
```
if you ask `can? :manage, review` this will return `false` but `Review.accessible_by(user) will return the review`. (see gist)

This is because of how `accessible_by` works and unfortunately there is no easy solution for that. The documentation is also misleading for such a case. The generated SQL query is the following:

```sql
SELECT "reviews".* 
FROM "reviews" 
LEFT OUTER JOIN "reviews_stores" ON "reviews_stores"."review_id" = "reviews"."id" 
LEFT OUTER JOIN "stores" ON "stores"."id" = "reviews_stores"."store_id" 
WHERE (
  not ("stores"."id" = 2) 
  AND 
("stores"."id" = 1))
```

the problem relies on the fact that all conditions are `or`d in the SQL. Since it performs a LEFT JOIN, all the reviews in store 1 will be fetched.

Now, there is not an easy solution for such a situation:
* we could change completely how we generate the SQL (see #518 ).
* we can update the documentation to highlight such a case.
* We may recognise such a case and abort `accessible_by` execution.

It's also true that this case never happened before because is rare that you define permission depending on an `has_many` association: that's why you are the first one in many years to find this issue.

Given that I will tackle this and I consider it a bug, I need to ask you feedback regarding your use case and why you need to do that. A real use case will help me understand how to tackle this and maybe suggest an alternative way. 

In such a situation I'd argue that if I am allowed to manage reviews in store 1 and not in store 2, the situation is ambiguous for a review that exists in both. Please try to explain to me the real use case. this would be appreciated. Thanks.

**Comment by coorasse** [comment]
Closing for lack of feedback. Please feel free to reopen or suggest a PR
