### ISSUE TITLE
Checking with Class vs an instance - question not an issue.

### ISSUE THREAD

**Issue by nfstern** [CanCanCommunity/cancancan#681]
According to the documentation:

Checking with Class

You can also pass the class instead of an instance (if you don't have one handy).

<% if can? :create, Project %>
  <%= link_to "New Project", new_project_path %>
<% end %>

Ok this is understandable, but is there a reason you should be checking with an instance vs a Class when you do have one? It seems to me, and I could be wrong, that what would happen here is that cancancan goes checks the class of the instance and then looks up the ability(ies) for that class. Why not just cut to the chase and use the class all the time? What am I missing here?

**Comment by matthee** [comment]
IMHO using a class depends on your use-case. If you have defined additional conditions in your ability, you may experience undesired behavior using classes alone. Using an instance allows you to explicitly setup your model beforehand and test more complex authorization schemes. 

Disclaimer: I've barely scratched the surface of what cancancan is capable of, and this advice is solely based on my experiences with this library so far 😉

**Comment by nfstern** [comment]
> If you have defined additional conditions in your ability, you may experience undesired behavior using classes alone.

Ok, fair enough. How about in the absence of additional ability conditions?

**Comment by andynu** [comment]
@matthee points at the main thing: conditions.

For :edit, or any conditions that need the details of an instance only an instance will do.

For example:
```
can :edit, Project do |project|
  project.user_id == user.id
end
```
or the same 
```
can :edit, Project, user_id: user.id
```

If there are no conditions, then it doesn't really matter. That's why it is fine for a :create check to use either Project or Project.new

@nfstern If you're satisfied with this then you might close this issue to help keep the open issues clean. Thanks.
